version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/openjdk:8u181-jdk-stretch
    working_directory: /home/circleci/project
    steps:
      - checkout
      - restore_cache:
          # if you ever need to invalidate the cache, simply bump the version number
          keys:
            - v1-maven-{{ .Branch }}-{{ checksum "pom.xml" }}
            - v1-maven-{{ .Branch }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-maven-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run: mvn package
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build docker image for testing
          command: docker build -t $CIRCLE_PROJECT_REPONAME ./target
      - run:
          name: Run test server container
          command: docker run -d -p 8080:8080 --name test-server $CIRCLE_PROJECT_REPONAME
      - run:
          name: Run Postman test collection using Newman container
          command: >
            docker run -v $CIRCLE_WORKING_DIRECTORY/test/postman:/etc/newman -t --network container:test-server
            postman/newman:alpine run "Airtime.postman_collection.json" --environment="test/postman/localhost.postman_environment.json"
  deploy:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
      HEROKU_APP: airtime-service-test-pack
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git master
  build-with-latest-deps:
    docker:
      - image: 813968012009.dkr.ecr.us-east-1.amazonaws.com/circleci-test-server
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout
      - restore_cache:
          # if you ever need to invalidate the cache, simply bump the version number
          keys:
            - v1-maven-{{ .Branch }}-{{ checksum "pom.xml" }}
            - v1-maven-{{ .Branch }}
      - run:
          name: Update pom with latest Electrum deps
          command: /electrum/bin/updatePomWithLatestDeps.sh
      - run:
          name: Test, but only if any Electrum dependencies changed
          command: /electrum/bin/postmanTestWithUpdatedDepsJava.sh
      - run:
          name: Notify success to slack
          command: /electrum/bin/notifySlackDepBuildSucceeded.sh
          when: on_success
      - run:
          name: Notify failure to slack
          command: /electrum/bin/notifySlackDepBuildFailed.sh
          when: on_fail

workflows:
  version: 2
  commit:
    jobs:
      - build-and-test:
          context: java
      - deploy-to-heroku:
          context: java
          requires:
            - build-and-test
          filters:
            branches:
              only: master
  nightly:
    jobs:
      - build-with-latest-deps:
          context: java
    triggers:
      - schedule:
          # every night at 00:00 SAST (22:00 UTC)
          cron: "00 22 * * *"
          filters:
            branches:
              only:
                - master
